
<?php 


$specs=$this->getRequest()->getParam('website');


print_r($this->getStoreInfo());

?>


<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3 class="icon-head"><?php echo Mage::helper('icecatcategories')->__('Additional Icecat Category Management') ?></h3></td><td class="form-buttons"></td>
         </tr>
    </table>
</div>
<table class="form-list">

<?php if(isset($specs)):?>
	<tr>
        <td class="scope-label">
          <button onclick="setLocation('<?php echo $this->addAdditionalCategories()?>')" type="button" class="scalable"><span><span><span><?php echo Mage::helper('adminhtml')->__('Import Additional Categories') ?></span></span></span></button>
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('icecatcategories')->__('Import additional categories to selected store.')?>
        </td>
    </tr>
    <tr>
        <td class="scope-label">
           <button onclick="confirmSetLocation('<?php echo $this->getMessage()?>','<?php echo $this->getRunSetupUrl()?>')" type="button" class="scalable"><span><span><span><?php echo Mage::helper('icecatcategories')->__('Run Setup') ?></span></span></span></button>
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('icecatcategories')->__('Re-Run Icecat! Categories Setup.')?>
        </td>
    </tr>
    <tr>
        <td class="scope-label">
           <button onclick="setLocation('<?php echo $this->getXmlManuallyUrl()?>')" type="button" class="scalable"><span><span><span><?php echo Mage::helper('adminhtml')->__('Get Icecat Xml File') ?></span></span></span></button>
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('icecatcategories')->__('Manually retreive XML file from Icecat.')?>
        </td>
    </tr>
     <?php else: ?> 
    <tr>
        <td class="scope-label">
        
         	<button onclick="alert('<?php echo $this->getMessageForStore()?>')" type="button" class="scalable"><span><span><span><?php echo Mage::helper('adminhtml')->__('Import Additional Categories') ?></span></span></span></button>
         
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('icecatcategories')->__('Import additional categories to selected store.')?>
        </td>
    </tr>
    <tr>
        <td class="scope-label">
       
        	<button onclick="alert('<?php echo $this->getMessageForStore()?>')" type="button" class="scalable"><span><span><span><?php echo Mage::helper('icecatcategories')->__('Run Setup') ?></span></span></span></button>
        
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('icecatcategories')->__('Re-Run Icecat! Categories Setup.')?>
        </td>
    </tr>
    <tr>
        <td class="scope-label">
        
         	<button onclick="alert('<?php echo $this->getMessageForStore()?>')" type="button" class="scalable"><span><span><span><?php echo Mage::helper('adminhtml')->__('Get Icecat Xml File') ?></span></span></span></button>
        
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('icecatcategories')->__('Manually retreive XML file from Icecat.')?>
        </td>
    </tr>
      <?php endif; ?>
    </table>



